export const FETCH_FOR_LAST_X_HOURS = 3 * 60 * 60 * 1000;

export const DISPLACEMENT_DANGER_THRESHOLD = 100;
export const DISPLACEMENT_WARNING_THRESHOLD = 80;

export const TEMPERATURE_DANGER_THRESHOLD = 50;
export const TEMPERATURE_WARNING_THRESHOLD = 45;

export const RMS_DANGER_THRESHOLD = 11;
export const RMS_WARNING_THRESHOLD = 7.1;
export const RMS_MEDIUM_THRESHOLD = 3.5;
